spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 10000