version: "3"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://auth-db -schemas=auth -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ../src/main/resources/flyway:/flyway/sql
    depends_on:
      - auth-db
  auth-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  auth-app:
    image: auth:0.0.1-SNAPSHOT
    depends_on:
      - auth-db
      - flyway
    ports:
      - 8080:8080
    volumes:
      - ./:/workspace/logs
